# Generated by Django 2.2.7 on 2020-06-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_closing',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_preface',
            field=models.TextField(),
        ),
    ]
